name: Vue

on:
  [ push ]

jobs:
  vue-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Jest Tests
        run: yarn test:unit-ci

      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
